export const GET_CHOCOS="GET_CHOCOS";
export const GET_BRANDS="GET_BRANDS";
export const GET_CHOCOS_SUCCESS="GET_CHOCOS_SUCCESS";
export const GET_CHOCOS_FAIL="GET_CHOCOS_FAIL";
export const GET_BRANDS_SUCCESS="GET_BRANDS_SUCCESS";
export const GET_BRANDS_FAIL="GET_BRANDS_FAIL";
export const GET_CHOCO_DETAILS = "GET_CHOCO_DETAILS";
export const GET_BRAND_DETAILS="GET_BRAND_DETAILS";
export const GET_CHOCO_DETAILS_SUCCESS = "GET_CHOCO_DETAILS_SUCCESS";
export const GET_BRAND_DETAILS_SUCCESS="GET_BRAND_DETAILS_SUCCESS";


